version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main" # The branch Dependabot will create PRs against
    open-pull-requests-limit: 5 # Limit the number of open PRs
    ignore:
      - dependency-name: "mysqlclient"
