# Generated by Django 5.1.4 on 2025-02-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgdvarianttypecomment',
            name='lgd_variant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gene2phenotype_app.lgdvarianttype'),
        ),
    ]
