# Generated by Django 5.1.5 on 2025-04-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gene2phenotype_app",
            "0003_remove_historicallocusattrib_attrib_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseExternal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("disease", models.CharField(max_length=255)),
                ("identifier", models.CharField(max_length=50)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gene2phenotype_app.source",
                    ),
                ),
            ],
            options={
                "db_table": "disease_external",
                "indexes": [
                    models.Index(
                        fields=["identifier"], name="disease_ext_identif_622f9d_idx"
                    )
                ],
                "unique_together": {("disease", "source")},
            },
        ),
    ]
