# Generated by Django 5.1.7 on 2025-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0004_diseaseexternal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genccsubmission',
            name='type_of_submission',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update')], default='create', max_length=50),
        ),
    ]