# Generated by Django 5.1.7 on 2025-06-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0004_diseaseexternal'),
        ('gene2phenotype_app', '0004_merge_20250414_1639'),
    ]

    operations = [
    ]
