# Generated by Django 5.1.7 on 2025-06-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0006_alter_genccsubmission_type_of_submission_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genccsubmission',
            name='unique_create_only',
        ),
        migrations.AlterUniqueTogether(
            name='genccsubmission',
            unique_together={('submission_id', 'g2p_stable_id')},
        ),
    ]
