# Generated by Django 5.1.10 on 2025-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0005_alter_genccsubmission_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="g2pstableid",
            name="comment",
            field=models.TextField(default=None, null=True),
        ),
    ]
