# Generated by Django 5.1.10 on 2025-07-04 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0006_g2pstableid_comment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="publicationfamilies",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="publicationfamilies",
            name="consanguinity",
        ),
        migrations.RemoveField(
            model_name="publicationfamilies",
            name="publication",
        ),
        migrations.AddField(
            model_name="historicallgdpublication",
            name="affected_individuals",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicallgdpublication",
            name="ancestry",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="historicallgdpublication",
            name="consanguinity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="gene2phenotype_app.attrib",
            ),
        ),
        migrations.AddField(
            model_name="historicallgdpublication",
            name="number_of_families",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lgdpublication",
            name="affected_individuals",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="lgdpublication",
            name="ancestry",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="lgdpublication",
            name="consanguinity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consanguinity_publication",
                to="gene2phenotype_app.attrib",
            ),
        ),
        migrations.AddField(
            model_name="lgdpublication",
            name="number_of_families",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="HistoricalPublicationFamilies",
        ),
        migrations.DeleteModel(
            name="PublicationFamilies",
        ),
    ]
