# Generated by Django 5.1.10 on 2025-08-01 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gene2phenotype_app",
            "0007_alter_publicationfamilies_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalPublicationComment",
            new_name="HistoricalLGDPublicationComment",
        ),
        migrations.AlterModelOptions(
            name="historicallgdpublicationcomment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical lgd publication comment",
                "verbose_name_plural": "historical lgd publication comments",
            },
        ),
        migrations.RemoveField(
            model_name="historicallgdpublicationcomment",
            name="publication",
        ),
        migrations.AddField(
            model_name="historicallgdpublicationcomment",
            name="lgd_publication",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="gene2phenotype_app.lgdpublication",
            ),
        ),
        migrations.CreateModel(
            name="LGDPublicationComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("is_public", models.SmallIntegerField(default=True)),
                ("is_deleted", models.SmallIntegerField(default=False)),
                ("date", models.DateTimeField()),
                (
                    "lgd_publication",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gene2phenotype_app.lgdpublication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lgd_publication_comment",
            },
        ),
        migrations.DeleteModel(
            name="PublicationComment",
        ),
    ]
