# Generated by Django 5.1.10 on 2025-08-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gene2phenotype_app",
            "0008_rename_historicalpublicationcomment_historicallgdpublicationcomment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lgdpublicationcomment",
            name="lgd_publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gene2phenotype_app.lgdpublication",
            ),
        ),
    ]
