# Generated by Django 5.1.10 on 2025-08-28 13:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0009_alter_lgdpublicationcomment_lgd_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMinedPublication',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('pmid', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('go_biological_process', models.TextField(default=None, null=True)),
                ('go_molecular_function', models.TextField(default=None, null=True)),
                ('reactome_pathways', models.TextField(default=None, null=True)),
                ('hpo_ids', models.TextField(default=None, null=True)),
                ('unweighted_hpo_ids', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('date_upload', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gene', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gene2phenotype_app.locus')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical mined publication',
                'verbose_name_plural': 'historical mined publications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MinedPublication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pmid', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('go_biological_process', models.TextField(default=None, null=True)),
                ('go_molecular_function', models.TextField(default=None, null=True)),
                ('reactome_pathways', models.TextField(default=None, null=True)),
                ('hpo_ids', models.TextField(default=None, null=True)),
                ('unweighted_hpo_ids', models.TextField(default=None, null=True)),
                ('text', models.TextField(default=None, null=True)),
                ('date_upload', models.DateTimeField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gene2phenotype_app.locus')),
            ],
            options={
                'db_table': 'mined_publication',
            },
        ),
        migrations.CreateModel(
            name='LGDMinedPublication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField(default=None, null=True)),
                ('lgd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gene2phenotype_app.locusgenotypedisease')),
                ('mined_publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gene2phenotype_app.minedpublication')),
            ],
            options={
                'db_table': 'lgd_mined_publication',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLGDMinedPublication',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField(default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lgd', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gene2phenotype_app.locusgenotypedisease')),
                ('mined_publication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gene2phenotype_app.minedpublication')),
            ],
            options={
                'verbose_name': 'historical lgd mined publication',
                'verbose_name_plural': 'historical lgd mined publications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='minedpublication',
            index=models.Index(fields=['pmid'], name='mined_publi_pmid_94af10_idx'),
        ),
        migrations.AddIndex(
            model_name='minedpublication',
            index=models.Index(fields=['gene'], name='mined_publi_gene_id_991300_idx'),
        ),
        migrations.AddIndex(
            model_name='lgdminedpublication',
            index=models.Index(fields=['lgd', 'mined_publication'], name='lgd_mined_p_lgd_id_1c6fb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='lgdminedpublication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['rejected', 'curated', 'mined'])), name='status_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='lgdminedpublication',
            unique_together={('lgd', 'mined_publication')},
        ),
    ]
