# Generated by Django 5.1.12 on 2025-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gene2phenotype_app",
            "0010_historicalminedpublication_minedpublication_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="locus",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="locusidentifier",
            unique_together={("identifier", "source")},
        ),
    ]
