# Generated by Django 5.1.13 on 2025-10-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0011_alter_locus_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalminedpublication",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="minedpublication",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
