# Generated by Django 5.1.14 on 2025-11-13 14:05

from django.db import migrations


def create_restricted_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    
    # Create the group if it doesn't exist
    Group.objects.get_or_create(name='junior_curator')
    Group.objects.get_or_create(name='expert_curator')
    Group.objects.get_or_create(name='curation_admin')
    Group.objects.get_or_create(name='clinical_lead')

class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0012_historicalminedpublication_year_and_more"),
    ]

    operations = [
        migrations.RunPython(create_restricted_group),
    ]
