# Generated by Django 5.1.14 on 2025-12-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0013_create_user_group"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lgdminedpublication",
            name="status_valid",
        ),
        migrations.AddField(
            model_name="historicallgdminedpublication",
            name="score",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicallgdminedpublication",
            name="score_comment",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="lgdminedpublication",
            name="score",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lgdminedpublication",
            name="score_comment",
            field=models.TextField(default=None, null=True),
        ),
    ]
