# Generated by Django 5.2.9 on 2026-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0014_historicallgdminedpublication_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curationdata",
            name="status",
            field=models.CharField(default="manual", max_length=50),
        ),
        migrations.AddField(
            model_name="historicalcurationdata",
            name="status",
            field=models.CharField(default="manual", max_length=50),
        ),
    ]
