# Generated by Django 5.2.9 on 2026-01-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gene2phenotype_app",
            "0015_curationdata_status_historicalcurationdata_status",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lgdminedpublication",
            name="score_valid",
        ),
        migrations.AddConstraint(
            model_name="lgdminedpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__in", ["high", "medium", "low", "disputed", "N/A", None])
                ),
                name="score_valid",
            ),
        ),
    ]
