# Generated by Django 5.2.9 on 2026-01-30 14:45

from django.db import migrations


def create_restricted_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    
    # Create the group if it doesn't exist
    Group.objects.get_or_create(name='g2p_admin')

class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0016_remove_lgdminedpublication_score_valid_and_more'),
    ]

    operations = [
        migrations.RunPython(create_restricted_group),
    ]
