# Generated by Django 5.2.11 on 2026-03-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0017_create_new_user_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenCCSubmission",
        ),
    ]
