# Generated by Django 5.2.9 on 2026-02-12 12:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0017_create_new_user_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="LGDReviewCase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("active_lgd_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("date_created", models.DateTimeField()),
                ("date_last_update", models.DateTimeField()),
                ("is_deleted", models.SmallIntegerField(default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases_assigned",
                        to="gene2phenotype_app.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cases_created",
                        to="gene2phenotype_app.user",
                    ),
                ),
                (
                    "lgd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gene2phenotype_app.locusgenotypedisease",
                    ),
                ),
            ],
            options={
                "db_table": "lgd_review_case",
            },
        ),
        migrations.CreateModel(
            name="HistoricalLGDReviewCase",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("active_lgd_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("date_created", models.DateTimeField()),
                ("date_last_update", models.DateTimeField()),
                ("is_deleted", models.SmallIntegerField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gene2phenotype_app.user",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gene2phenotype_app.user",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lgd",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gene2phenotype_app.locusgenotypedisease",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical lgd review case",
                "verbose_name_plural": "historical lgd review cases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LGDReviewItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("disease", "Disease"),
                            ("mechanism", "Molecular mechanism"),
                            ("genotype", "Allelic requirement"),
                            ("confidence", "Confidence"),
                            ("publications", "Publications"),
                            ("phenotypes", "Phenotypes"),
                            ("variant_type", "Variant type"),
                            ("variant_consequence", "Variant consequence"),
                            ("cross_cutting_modifier", "Cross cutting modifier"),
                            ("panel", "Panel"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("is_deleted", models.SmallIntegerField(default=False)),
                (
                    "active_component_key",
                    models.CharField(blank=True, max_length=150, null=True, unique=True),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gene2phenotype_app.lgdreviewcase",
                    ),
                ),
            ],
            options={
                "db_table": "lgd_review_item",
            },
        ),
        migrations.CreateModel(
            name="HistoricalLGDReviewItem",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("disease", "Disease"),
                            ("mechanism", "Molecular mechanism"),
                            ("genotype", "Allelic requirement"),
                            ("confidence", "Confidence"),
                            ("publications", "Publications"),
                            ("phenotypes", "Phenotypes"),
                            ("variant_type", "Variant type"),
                            ("variant_consequence", "Variant consequence"),
                            ("cross_cutting_modifier", "Cross cutting modifier"),
                            ("panel", "Panel"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("is_deleted", models.SmallIntegerField(default=False)),
                (
                    "active_component_key",
                    models.CharField(blank=True, db_index=True, max_length=150, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_case",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gene2phenotype_app.lgdreviewcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical lgd review item",
                "verbose_name_plural": "historical lgd review items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="lgdreviewcase",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "in_review", "resolved"])),
                name="lgd_review_case_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="lgdreviewcase",
            index=models.Index(fields=["lgd"], name="lgd_review_c_lgd_id_9220e7_idx"),
        ),
        migrations.AddIndex(
            model_name="lgdreviewcase",
            index=models.Index(
                fields=["status"], name="lgd_review_c_status_c88b4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lgdreviewcase",
            index=models.Index(
                fields=["assigned_to"], name="lgd_review_c_assigne_5d9902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lgdreviewcase",
            index=models.Index(
                fields=["is_deleted"], name="lgd_review_c_is_dele_6fd7ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lgdreviewitem",
            index=models.Index(
                fields=["review_case"], name="lgd_review_i_review__909cd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lgdreviewitem",
            index=models.Index(
                fields=["component"], name="lgd_review_i_compone_8abec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lgdreviewitem",
            index=models.Index(
                fields=["is_deleted"], name="lgd_review_i_is_dele_a5f969_idx"
            ),
        ),
    ]
