# Generated by Django 5.2.11 on 2026-05-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gene2phenotype_app", "0019_historicallgdreviewcase_lgdreviewcase_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="uniprotannotation",
            name="uniprot_ann_uniprot_c49c17_idx",
        ),
        migrations.RemoveIndex(
            model_name="uniprotannotation",
            name="uniprot_ann_hgnc_190d1c_idx",
        ),
        migrations.RemoveField(
            model_name="uniprotannotation",
            name="gene_symbol",
        ),
        migrations.RemoveField(
            model_name="uniprotannotation",
            name="hgnc",
        ),
        migrations.RemoveField(
            model_name="uniprotannotation",
            name="mim",
        ),
        migrations.AddField(
            model_name="uniprotannotation",
            name="data_type",
            field=models.ForeignKey(
                default=65, # attrib "uniprot_protein_function"
                on_delete=django.db.models.deletion.PROTECT,
                to="gene2phenotype_app.attrib",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="uniprotannotation",
            index=models.Index(fields=["gene"], name="uniprot_ann_gene_id_9b16f6_idx"),
        ),
        migrations.AddIndex(
            model_name="uniprotannotation",
            index=models.Index(
                fields=["data_type"], name="uniprot_ann_data_ty_fcc0a6_idx"
            ),
        ),
    ]
