# Generated by Django 5.2.14 on 2026-07-13 15:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0020_remove_uniprotannotation_uniprot_ann_uniprot_c49c17_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLGDVariantTypePublication',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_deleted', models.SmallIntegerField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lgd_variant_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gene2phenotype_app.lgdvarianttype')),
                ('publication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gene2phenotype_app.publication')),
            ],
            options={
                'verbose_name': 'historical lgd variant type publication',
                'verbose_name_plural': 'historical lgd variant type publications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LGDVariantTypePublication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.SmallIntegerField(default=False)),
                ('lgd_variant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='gene2phenotype_app.lgdvarianttype')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gene2phenotype_app.publication')),
            ],
            options={
                'db_table': 'lgd_variant_type_publication',
                'unique_together': {('lgd_variant_type', 'publication')},
            },
        ),
    ]
