# Generated by Django 5.2.14 on 2026-07-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gene2phenotype_app', '0022_populate_lgd_variant_type_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallgdvarianttype',
            name='publication',
        ),
        migrations.AlterUniqueTogether(
            name='lgdvarianttype',
            unique_together={('lgd', 'variant_type_ot')},
        ),
        migrations.RemoveField(
            model_name='lgdvarianttype',
            name='publication',
        ),
    ]
